import { ScanResult } from "@/types/index";

// Score breakdown: PASS=58pts, WARN=14.5pts (half weight), FAIL=0pts → 72.5/155 = 47
export const SAMPLE_REPORT: ScanResult = {
  url: "https://example-agency.com",
  score: 47,
  unlocked: true,
  scannedAt: "2026-05-16T10:00:00.000Z",
  metadata: {
    title: "Example Agency - Digital Marketing for Local Businesses",
    metaDescription: "",
    ogTitle: "Example Agency - Digital Marketing for Local Businesses",
    ogDescription: "",
    ogImage: "",
    canonical: "https://example-agency.com",
    h1: "Digital Marketing for Local Businesses",
  },
  pagespeed: {
    score: 61,
    lcp: 3.2,
    cls: 0.08,
    fid: 180,
  },
  aiInsights: {
    summary:
      "This page presents Example Agency's digital marketing services for local businesses. The title and H1 are clear, but missing schema, a blocked AI crawler, and thin content limit how confidently AI systems can summarize and cite this page.",
    recommendations: [
      "Add Organization and WebSite JSON-LD schema to establish your brand entity for AI engines.",
      "Write a 120-155 character meta description describing your services and target clients.",
      "Create an llms.txt file at your domain root to give AI crawlers direct context about your site.",
      "Remove the GPTBot block from robots.txt so ChatGPT can crawl and cite your pages.",
      "Expand page content beyond 300 words and add a FAQ section with FAQPage schema.",
    ],
    quickWin:
      "Add a meta description - it takes under 5 minutes and immediately improves how AI systems summarize and label this page in answers.",
    contentGap:
      "The page lacks structured data, author attribution, and dateModified signals. AI engines cannot confirm who published this content or when it was last updated.",
    schemaRecommendations: {
      detected: ["Not detected from page content."],
      missing: ["Organization", "WebSite", "WebPage", "FAQPage", "LocalBusiness"],
      priority: "Organization",
      reasoning:
        "Organization schema establishes your brand entity, making it easier for AI systems to connect your content to a trusted, named source.",
    },
  },
  checks: [
    {
      id: "title",
      label: "Page Title",
      status: "pass",
      detail: "Title is 54 characters: 'Example Agency - Digital Marketing for Local Businesses'.",
      weight: 8,
    },
    {
      id: "meta_desc",
      label: "Meta Description",
      status: "fail",
      detail: "No meta description found. AI systems will auto-generate one from page content, often pulling the wrong text.",
      weight: 8,
    },
    {
      id: "h1",
      label: "H1 Heading",
      status: "pass",
      detail: "H1 found: 'Digital Marketing for Local Businesses'.",
      weight: 8,
    },
    {
      id: "heading_structure",
      label: "Heading Structure",
      status: "warn",
      detail: "Heading hierarchy has gaps - H3 elements appear without H2 parents in 2 sections.",
      weight: 5,
    },
    {
      id: "schema_present",
      label: "Schema Markup",
      status: "fail",
      detail: "No JSON-LD schema detected. AI systems cannot confirm the page type, entity, or author.",
      weight: 10,
    },
    {
      id: "faq_schema",
      label: "FAQ Schema",
      status: "fail",
      detail: "FAQ content exists on the page but is not wrapped in FAQPage schema. AI systems cannot extract it as structured answers.",
      weight: 10,
    },
    {
      id: "article_schema",
      label: "Article Schema",
      status: "fail",
      detail: "No Article or BlogPosting schema detected. Add Article schema with datePublished if this page contains authored content.",
      weight: 7,
    },
    {
      id: "og_tags",
      label: "Open Graph Tags",
      status: "pass",
      detail: "OG title is present and matches the page title.",
      weight: 6,
    },
    {
      id: "og_image",
      label: "OG Image",
      status: "fail",
      detail: "No Open Graph image set. Shared or cited pages without an OG image display a blank placeholder.",
      weight: 4,
    },
    {
      id: "https",
      label: "HTTPS",
      status: "pass",
      detail: "Page is served securely over HTTPS.",
      weight: 8,
    },
    {
      id: "robots",
      label: "Robots.txt",
      status: "pass",
      detail: "robots.txt found and allows major crawlers.",
      weight: 5,
    },
    {
      id: "ai_bot_access",
      label: "AI Bot Access",
      status: "fail",
      detail: "GPTBot is blocked in robots.txt. ChatGPT cannot crawl or cite this page.",
      weight: 8,
    },
    {
      id: "sitemap",
      label: "XML Sitemap",
      status: "pass",
      detail: "Sitemap found at /sitemap.xml and includes this page.",
      weight: 5,
    },
    {
      id: "llms_txt",
      label: "llms.txt File",
      status: "fail",
      detail: "No llms.txt found at the domain root. AI engines have no explicit context about this site's purpose or key pages.",
      weight: 9,
    },
    {
      id: "alt_text",
      label: "Image Alt Text",
      status: "warn",
      detail: "4 of 11 images are missing alt text. These images are invisible to AI vision systems and crawlers.",
      weight: 6,
    },
    {
      id: "word_count",
      label: "Word Count",
      status: "warn",
      detail: "Page has 218 words. Thin pages are rarely chosen as AI citation sources. Target 300+ words.",
      weight: 7,
    },
    {
      id: "internal_links",
      label: "Internal Links",
      status: "pass",
      detail: "6 internal links found. Good crawl and topic clustering signal.",
      weight: 4,
    },
    {
      id: "structured_density",
      label: "Schema Density",
      status: "fail",
      detail: "No structured data found. Pages with multiple schema types receive more accurate AI citations.",
      weight: 5,
    },
    {
      id: "eeat_author",
      label: "Author Attribution",
      status: "fail",
      detail: "No author byline or Person schema detected. AI engines cannot attribute this content to a named expert.",
      weight: 7,
    },
    {
      id: "eeat_about",
      label: "About / Contact Pages",
      status: "pass",
      detail: "About and Contact pages are linked in the site navigation.",
      weight: 8,
    },
    {
      id: "eeat_freshness",
      label: "Content Freshness",
      status: "warn",
      detail: "No datePublished or dateModified found in schema or meta tags. AI engines may deprioritize this page as stale.",
      weight: 5,
    },
    {
      id: "readability",
      label: "Readability",
      status: "pass",
      detail: "Flesch score: 68. Good readability - clear writing supports AI extraction and summarization.",
      weight: 6,
    },
    {
      id: "core_web_vitals",
      label: "Core Web Vitals",
      status: "warn",
      detail: "PageSpeed score 61. LCP is 3.2s - above the 2.5s target. CLS is 0.08 - within acceptable range.",
      weight: 6,
    },
  ],
};
